server:
  port: 80

spring:
  application:
    name: glz-shop-gateway
  cloud:
    nacos:
      server-addr: 39.106.162.221:8848
    gateway:
      routes:
        - id: glz-shop-inventory
          uri: lb://glz-shop-inventory
          predicates:
            - Path=/inventory/**

        - id: glz-shop-sso
          uri: lb://glz-shop-sso
          predicates:
            - Path=/auth/**,/logout
        - id: glz-shop-user
          uri: lb://glz-shop-user
          predicates:
            - Path=/role/**,/role/menu/**,/user/**,/role/user/**,/menu/**,/member/**

        - id: glz-shop-commodity
          uri: lb://glz-shop-commodity
          predicates:
            - Path=/commodity/**,/commodityCategory/**,/commodityAttribute/**,/commodityVertityRecord/**

