

spring:
  application:
    name: glz-shop-user
  datasource:
    username: admin
    password: shop1234
    url: jdbc:mysql://39.106.162.221:3306/glz-shop
  cloud:
    nacos:
      discovery:
        server-addr: 39.106.162.221:8848

dubbo:
  scan:
    base-packages: com.smy.shop.service.impl
  protocols:
    dubbo:
      port: -1

server:
  port: 10001

management:
  endpoints:
    web:
      exposure:
        include: dubborestmetadata
