server:
  port: 80

spring:
  application:
    name: glz-shop-gateway
  cloud:
    nacos:
      server-addr: 39.106.162.221:8848
    gateway:
      routes:
        - id: glz-shop-inventory
          uri: lb://glz-shop-inventory
          predicates:
            - Path=/inventory/**
        - id: glz-shop-sso
          uri: lb://glz-shop-sso
          predicates:
            - Path=/auth/**,/logout

        - id: glz-shop-user
          uri: lb://glz-shop-user
          predicates:
            - Path=/role/**,/role/menu/**,/user/**,/role/user/**,/menu/**,/member/**

        - id: glz-shop-commodity
          uri: lb://glz-shop-commodity
          predicates:
            - Path=/commodity/**,/commodityCategory/**,/commodityAttribute/**,/commodityVertityRecord/**

        - id: glz-shop-order
          uri: lb://glz-shop-order
          predicates:
            - Path=/ship/**,/orderBack/**,/order/**,/orderItem/**,/orderFile/**

        - id: glz-shop-cart-service
          uri: lb://glz-shop-cart-service
          predicates:
            - Path=/cart/**

        - id: glz-shop-advertise
          uri: lb://glz-shop-advertise
          predicates:
            - Path=/shop/adver/**,/file/**

        - id: glz-shop-newProduct
          uri: lb://glz-shop-newProduct
          predicates:
            - Path=/shop/newProduct/**

        - id: glz-shop-collect
          uri: lb://glz-shop-collect
          predicates:
            - Path=/shop/**
