server:
  port: 80

spring:
  application:
    name: glz-shop-gateway
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
#    gateway:
#      routes:
#        - id:
#          uri:
#          predicates:
#            - Path=/user/**
